_attn_implementation_autoset:
    value: true
_name_or_path:
    value: ""
_wandb:
    value:
        cli_version: 0.18.7
        m:
            - "1": train/global_step
              "6":
                - 3
              "7": []
            - "1": train/loss
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": train/grad_norm
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": train/learning_rate
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": train/epoch
              "5": 1
              "6":
                - 1
                - 3
              "7": []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 5
                - 11
                - 29
                - 41
                - 49
                - 50
                - 51
                - 53
                - 55
                - 71
                - 98
                - 105
            "2":
                - 1
                - 5
                - 11
                - 29
                - 41
                - 49
                - 50
                - 51
                - 53
                - 55
                - 71
                - 98
                - 105
            "3":
                - 7
                - 13
                - 19
                - 23
                - 55
                - 66
            "4": 3.12.9
            "5": 0.18.7
            "6": 4.46.0
            "8":
                - 5
            "9":
                "1": transformers_trainer
            "12": 0.18.7
            "13": linux-x86_64
Ubit:
    value: 100
accelerator_config:
    value:
        dispatch_batches: null
        even_batches: true
        gradient_accumulation_kwargs: null
        non_blocking: false
        split_batches: false
        use_seedable_sampler: true
adafactor:
    value: false
adam_beta1:
    value: 0.9
adam_beta2:
    value: 0.999
adam_epsilon:
    value: 1e-08
add_cross_attention:
    value: false
architectures:
    value:
        - Qwen2ForCausalLM
auto_find_batch_size:
    value: false
babit:
    value: E5M2
bad_words_ids:
    value: null
batch_eval_metrics:
    value: false
begin_suppress_tokens:
    value: null
bf16:
    value: true
bf16_full_eval:
    value: false
bits:
    value: 16
bobit:
    value: E5M2
bos_token_id:
    value: null
bwbit:
    value: E5M2
cache_dir:
    value: null
chat_template:
    value: qwen2
chunk_size_feed_forward:
    value: 0
col_blocksize:
    value: -1
col_blocksize_optimizer:
    value: 128
cross_attention_hidden_size:
    value: null
data_seed:
    value: null
dataloader_drop_last:
    value: false
dataloader_num_workers:
    value: 8
dataloader_persistent_workers:
    value: false
dataloader_pin_memory:
    value: true
dataloader_prefetch_factor:
    value: null
ddp_backend:
    value: null
ddp_broadcast_buffers:
    value: null
ddp_bucket_cap_mb:
    value: null
ddp_find_unused_parameters:
    value: null
ddp_timeout:
    value: 1800
debug:
    value: []
debug_e2e:
    value: false
decoder_start_token_id:
    value: null
deepspeed:
    value: scripts/zero3.json
disable_tqdm:
    value: false
dispatch_batches:
    value: null
diversity_penalty:
    value: 0
do_eval:
    value: false
do_predict:
    value: false
do_sample:
    value: false
do_train:
    value: false
double_quant:
    value: true
dpo:
    value: false
dpo_beta:
    value: 0.1
draw_distribution_backward:
    value: false
draw_distribution_forward:
    value: false
drop_path_rate:
    value: 0
dynamic_s2:
    value: false
early_stopping:
    value: false
encoder_no_repeat_ngram_size:
    value: 0
eos_token_id:
    value: null
epsilon:
    value: 1e-10
epsilon_optimizer:
    value: 1e-15
eval_accumulation_steps:
    value: null
eval_delay:
    value: 0
eval_do_concat_batches:
    value: true
eval_on_start:
    value: false
eval_steps:
    value: null
eval_strategy:
    value: "no"
eval_use_gather_object:
    value: false
evaluation_strategy:
    value: "no"
exponential_decay_length_penalty:
    value: null
fabit:
    value: E4M3
finetuning_task:
    value: null
first_order_bit:
    value: null
first_order_quant_type:
    value: null
fobit:
    value: E4M3
forced_bos_token_id:
    value: null
forced_eos_token_id:
    value: null
fp16:
    value: false
fp16_backend:
    value: auto
fp16_full_eval:
    value: false
fp16_opt_level:
    value: O1
fsdp:
    value: []
fsdp_config:
    value:
        min_num_params: 0
        xla: false
        xla_fsdp_grad_ckpt: false
        xla_fsdp_v2: false
fsdp_min_num_params:
    value: 0
fsdp_transformer_layer_cls_to_wrap:
    value: null
full_determinism:
    value: false
fwbit:
    value: E4M3
gradient_accumulation_steps:
    value: 1
gradient_checkpointing:
    value: true
gradient_checkpointing_kwargs:
    value: null
greater_is_better:
    value: null
group_by_length:
    value: false
group_by_modality_length:
    value: false
group_size:
    value: -1
half_precision_backend:
    value: auto
hidden_size:
    value: 3584
hub_always_push:
    value: false
hub_model_id:
    value: null
hub_private_repo:
    value: false
hub_strategy:
    value: every_save
hub_token:
    value: <HUB_TOKEN>
id2label:
    value:
        "0": LABEL_0
        "1": LABEL_1
ignore_data_skip:
    value: false
include_for_metrics:
    value: []
include_inputs_for_metrics:
    value: false
include_num_input_tokens_seen:
    value: false
include_tokens_per_second:
    value: false
is_decoder:
    value: false
is_encoder_decoder:
    value: false
jit_mode_eval:
    value: false
label_names:
    value: null
label_smoothing_factor:
    value: 0
label2id:
    value:
        LABEL_0: 0
        LABEL_1: 1
learning_rate:
    value: 0.001
length_column_name:
    value: length
length_penalty:
    value: 1
llm_cfg:
    value: /lustre/fsw/portfolios/adlr/users/arushig/video_llm/mllm/Qwen2.5-7B-Instruct
load_best_model_at_end:
    value: false
local_rank:
    value: 0
log_level:
    value: passive
log_level_replica:
    value: warning
log_on_each_node:
    value: true
logging_dir:
    value: runs/train/stage1_af3/runs/Oct16_23-35-19_batch-block4-2016
logging_first_step:
    value: false
logging_nan_inf_filter:
    value: true
logging_steps:
    value: 1
logging_strategy:
    value: steps
longvila_sampler:
    value: false
lora_alpha:
    value: 16
lora_bias:
    value: none
lora_dropout:
    value: 0.05
lora_enable:
    value: false
lora_llm:
    value: false
lora_r:
    value: 64
lora_sot:
    value: false
lora_weight_path:
    value: ""
lr_scheduler_type:
    value: cosine
max_grad_norm:
    value: 1
max_length:
    value: 20
max_steps:
    value: -1
metric_for_best_model:
    value: null
min_blockunit_col:
    value: 4
min_blockunit_row:
    value: 4
min_length:
    value: 0
mlp_path:
    value: null
mm_use_im_patch_token:
    value: false
mm_use_im_start_end:
    value: false
model/num_parameters:
    value: 0
model_dtype:
    value: torch.bfloat16
model_max_length:
    value: 8192
model_name_or_path:
    value: /lustre/fsw/portfolios/adlr/users/arushig/video_llm/mllm/Qwen2.5-7B-Instruct
model_type:
    value: llava_llama
mp_parameters:
    value: ""
mpt_attn_impl:
    value: triton
neftune_noise_alpha:
    value: null
no_cuda:
    value: false
no_repeat_ngram_size:
    value: 0
num_beam_groups:
    value: 1
num_beams:
    value: 1
num_return_sequences:
    value: 1
num_time_tokens:
    value: 0
num_train_epochs:
    value: 1
optim:
    value: adamw_torch
optim_args:
    value: null
optim_target_modules:
    value: null
output_attentions:
    value: false
output_dir:
    value: runs/train/stage1_af3
output_hidden_states:
    value: false
output_scores:
    value: false
overwrite_output_dir:
    value: false
pad_block:
    value: false
pad_to_multiple_of:
    value: 0
pad_token_id:
    value: null
past_index:
    value: -1
per_device_eval_batch_size:
    value: 8
per_device_train_batch_size:
    value: 4
per_gpu_eval_batch_size:
    value: null
per_gpu_train_batch_size:
    value: null
pre_terminate_time:
    value: 10
prediction_loss_only:
    value: false
prefix:
    value: null
problem_type:
    value: null
push_to_hub:
    value: false
push_to_hub_model_id:
    value: null
push_to_hub_organization:
    value: null
push_to_hub_token:
    value: <PUSH_TO_HUB_TOKEN>
qchoice:
    value: none
quant_type:
    value: nf4
quantize_model:
    value: false
ray_scope:
    value: last
refine_attn_blocksize:
    value: false
refine_col_blocksize:
    value: 4
refine_ln_blocksize:
    value: false
refine_ln_blocksize_but_only_backward:
    value: false
refine_ln_blocksize_but_only_forward:
    value: false
refine_ln_pertoken:
    value: false
refine_mlp_blocksize:
    value: false
refine_residual_fp:
    value: false
refine_row_blocksize:
    value: 4
remove_invalid_values:
    value: false
remove_unused_columns:
    value: false
repetition_penalty:
    value: 1
report_to:
    value:
        - wandb
restore_callback_states_from_checkpoint:
    value: false
resume_from_checkpoint:
    value: null
resume_path:
    value: null
return_dict:
    value: true
return_dict_in_generate:
    value: false
row_blocksize:
    value: -1
row_blocksize_optimizer:
    value: 1
run_name:
    value: stage1_af3
s2:
    value: false
s2_max_split_size:
    value: 336
s2_resize_output_to_scale_idx:
    value: 0
s2_scales:
    value: 336,672,1008
save_on_each_node:
    value: false
save_only_model:
    value: false
save_safetensors:
    value: true
save_steps:
    value: 100
save_strategy:
    value: steps
save_total_limit:
    value: 3
second_order_bit:
    value: null
second_order_quant_type:
    value: null
seed:
    value: 42
sep_token_id:
    value: null
seq_parallel_ring_size:
    value: -1
seq_parallel_ring_type:
    value: ring_varlen
seq_parallel_size:
    value: -1
skip_memory_metrics:
    value: true
soft_ce_std:
    value: 1
sound_encoder:
    value:
        _target_: llava.model.encoders.BasicSoundEncoder
sound_hidden_size:
    value: 1280
sound_mm_projector:
    value: mlp
sound_mm_projector_cfg:
    value: mlp
sound_mm_projector_lr:
    value: null
sound_tower:
    value: openai/whisper-large-v3
sound_tower_cfg:
    value: openai/whisper-large-v3
sound_tower_lr:
    value: null
split_batches:
    value: null
suppress_tokens:
    value: null
symm:
    value: true
task_specific_params:
    value: null
temperature:
    value: 1
tf_legacy_loss:
    value: false
tf32:
    value: null
tie_encoder_decoder:
    value: false
tie_word_embeddings:
    value: true
time_token_format:
    value: <t{t}>
time_token_ids:
    value: []
tokenizer_class:
    value: null
top_k:
    value: 50
top_p:
    value: 1
torch_compile:
    value: false
torch_compile_backend:
    value: null
torch_compile_mode:
    value: null
torch_dtype:
    value: null
torch_empty_cache_steps:
    value: null
torchdynamo:
    value: null
torchscript:
    value: false
total_time_limit:
    value: -1
tpu_metrics_debug:
    value: false
tpu_num_cores:
    value: null
transformers_version:
    value: 4.46.0
tune_language_model:
    value: false
tune_sound_mm_projector:
    value: true
tune_sound_tower:
    value: false
typical_p:
    value: 1
use_bfloat16:
    value: false
use_cpu:
    value: false
use_dora:
    value: false
use_ipex:
    value: false
use_legacy_prediction_loop:
    value: false
use_liger_kernel:
    value: false
use_mps_device:
    value: false
use_one_logger:
    value: false
use_quantize_optimizer:
    value: false
version:
    value: auto
warmup_ratio:
    value: 0.03
warmup_steps:
    value: 0
weight_decay:
    value: 0
weight_memory_efficient:
    value: true
